# Generated by Django 4.2.4 on 2023-09-01 15:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('telling_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='quotes',
            old_name='book_id',
            new_name='book',
        ),
    ]
