# Generated by Django 4.2.4 on 2023-09-02 20:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('telling_app', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Questions',
        ),
    ]
