# Generated by Django 4.2.4 on 2023-09-01 15:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('telling_app', '0002_rename_book_id_quotes_book'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quotes',
            name='book',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='telling_app.book'),
        ),
    ]
